### ISSUE TITLE
get_movie() is returning a list, not JSON

### ISSUE THREAD

**Issue by Gestas** [totaldebug/pyarr#107]
## Expected behavior
get_movie() should return a JSON formatted string/object. 

## Current behavior
get_movie() is not returning valid JSON. 

## Possible reasons and solutions
[_request_get](https://github.com/totaldebug/pyarr/blob/a90e267905c192dc4a96ffb46d9582537dbbd45b/pyarr/request_handler.py#L58) and [_process_response](https://github.com/totaldebug/pyarr/blob/a90e267905c192dc4a96ffb46d9582537dbbd45b/pyarr/request_handler.py#L162) aren't handling some unexpected (to me at least) behavior by the requests package. For some reason requests is returning properly formatted json in the _res.text_ object, *not* _res.json()_. See this simple repro of requests behavior - 
```
#! /usr/local/bin/python3.8
import requests

_host_url = 'https://myhost'
_api_key = 'foo'
_movieid = 530915
_url = f"{_host_url}/api/v3/movie?tmdbId={_movieid}&apikey={_api_key}"

res = requests.get(url=_url)
print(res.text)
print("\n-----------------------------------\n")
print(res.json())
```
The output looks like this (truncated) - 
```
[
  {
    "title": "1917",
    "originalTitle": "1917",
    "originalLanguage": {
      "id": 1,
      "name": "English"
    },
    "alternateTitles": [
      {
        "sourceType": "tmdb",
        "movieId": 887,
        "title": "April 6 1917",
        "sourceId": 530915,
#### Valid JSON completes ###

-----------------------------------

[{'title': '1917', 'originalTitle': '1917', 'originalLanguage': {'id': 1, 'name': 'English'}, 'alternateTitles': [{'sourceType': 'tmdb', 'movieId': 887, 'title': 'April 6 1917', 'sourceId': 530915,
#### List continues ####
```

## Steps to reproduce
Simple repro based on the _get_movie()_ example here - https://docs.totaldebug.uk/pyarr/radarr.html
```
#! /usr/local/bin/python3.8
from pyarr import RadarrAPI

_host_url = ''https://myhost'
_api_key = 'foo'
_movieid = 530915

radarr = RadarrAPI(_host_url, _api_key)
movie = radarr.get_movie(_movieid)
print(movie)
```
Results in (truncated) - 
```
[{'title': '1917', 'originalTitle': '1917', 'originalLanguage': {'id': 1, 'name': 'English'}, 'alternateTitles': [{'sourceType': 'tmdb', 'movieId': 887, 'title': 'April 6 1917', 'sourceId': 530915, 'votes': 0, 'voteCount': 0, 'language': {'id': 1, 'name': 'English'}, 'id': 1053}, {'sourceType': 'tmdb', 'movieId': 887, 'title': '일구일칠', 'sourceId': 0, 'votes': 0, 'voteCount': 0, 'language': {'id': 1, 'name': 'English'}, 'id': 1407}, {'sourceType': 'tmdb', 'movieId': 887, 'title': '一九一七', 'sourceId': 0, 'votes': 0, 'voteCount': 0, 'language': {'id': 1, 'name': 'English'}, 'id': 1408}, {'sourceType': 'tmdb', 'movieId': 887, 'title': '1917：逆战救兵', 'sourceId': 0, 'votes': 0, #### List continues ####
```

## Context
The response isn't reasonably consumable as a list of strings.

## Your environment
* Radarr version 4.1.0.6175 
* Python 3.8
* $ pip3.8 show pyarr
Name: pyarr
Version: 3.1.3
* $ pip3.8 show requests
Name: requests
Version: 2.28.0

## Checklist
- [x ] I searched the current issues and the issue is not known.
- [x ] I searched the troubleshooting and there's no fix available for this bug.
- [x ] I searched on Google, YouTube, Reddit and there's no fix.
- [x ] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
Hi there,

`.json()` returns a JSON response in Python dictionary format so we can access JSON using key-value pairs. 

Hope that this helps.
