### ISSUE TITLE
Type hint errors

### ISSUE THREAD

**Issue by wthueb** [totaldebug/pyarr#111]
Dropped v4.0.1 into my project, and decided to see what Pylance says doesn't work.

`RadarrAPI.add_movie` should take a `db_id: Union[str, int]` since IMDB IDs are `str`s and TMDB IDs are `int`s (or at least those are the types returned by `RadarrAPI.lookup_movie`). This propagates to `RadarrAPI._movie_json` and `RadarrAPI.lookup_movie_by_tmdb_id`.

`RadarrAPI.get_tag_detail` should return `Union[list[dict[str, Any]], dict[str, Any]]` since as the docstring points out, "Returns all tags or specific tag by database id with detailed information".

`SonarrAPI.get_series` should return `Union[list[dict[str, Any]], dict[str, Any]]`: "Returns all series in your collection or the series with the matching series ID if one is found."

Also, to import `RadarrCommands`, should that be exposed at the top level `pyarr` package? Having to do `from pyarr.models.radarr import RadarrCommands` seems a bit esoteric (as well as `SonarrCommands`).

**Comment by wthueb** [comment]
Mostly unrelated to this, I think there's a mixup between using `db_id` as a parameter like in `RadarrAPI.add_movie` (TMDB/IMDB ID based on if `tmbd: bool`) and using `id_` as a parameter in `RadarrAPI.get_movie` (also a TMDB ID, no support for IMDB ID). Meanwhile, `RadarrAPI.del_movie` takes an `id_` which is a Radarr database ID (`movie_json['id']`) instead of a TMDB/IMDB ID. Not sure if this applies elsewhere in the codebase/with other APIs, these are just the functions I've noticed the mismatch.

**Comment by wthueb** [comment]
Ah, one last thing. `RadarrAPI.get_movie_by_movie_id` is annotated as `list[dict[str, Any]]` when it should just be `dict[str, Any]`.

**Comment by marksie1988** [comment]
> Mostly unrelated to this, I think there's a mixup between using `db_id` as a parameter like in `RadarrAPI.add_movie` (TMDB/IMDB ID based on `tmbd: bool`) and using `id_` as a parameter in `RadarrAPI.get_movie` (also a TMDB ID, no support for IMDB ID). Meanwhile, `RadarrAPI.del_movie` takes an `id_` which is a Radarr database ID (`movie_json['id']`) instead of a TMDB/IMDB ID. Not sure if this applies elsewhere in the codebase/with other APIs, these are just the functions I've noticed the mismatch.

Yes I agree there are some consistency issues with the naming of args etc. I will go through this at some point. However based on this I think the next think I look into will be setting up tests, not something ive done before but think it is necessary to avoid a lot of these issues.
