### ISSUE TITLE
Enforce Path Correctness

### ISSUE THREAD

**Issue by Archmonger** [totaldebug/pyarr#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected feature

Currently, the user can type in paths for "host_url" or "ver_uri" that can cause unexpected behavior.

### Possible Solutions

Run `rstrip("/")` on user inputted values, where we are already putting slashes in via f-strings.

### Context / Reason

Enforce good practices within the framework to prevent issue tickets.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
This has been added and will be in release 5.0.0
