### ISSUE TITLE
rootfolder improvement

### ISSUE THREAD

**Issue by Fuochi** [totaldebug/pyarr#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected feature

- get a specific root folder via its ID
- add missing method in radarr and sonarr to create a root folder

### Possible Solutions

creating a PR soon

### Context / Reason

it'll help manage rootfolders via API

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
This has been added to #116

**Comment by marksie1988** [comment]
This has now been added and will be in release 5.0.0
