### ISSUE TITLE
List import

### ISSUE THREAD

**Issue by kindofausername** [totaldebug/pyarr#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected feature

Api call to start list import in radarr.

### Possible Solutions

Api call to trigger list import in radarr.

### Context / Reason

It would be cool, if we could start a list import. Can't figure out how to use the "post_command" to make radarr update a list.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
This will be added as part of #116

**Comment by marksie1988** [comment]
This has been added and will be in release 5.0.0
