### ISSUE TITLE
Radarr: manualimport endpoint

### ISSUE THREAD

**Issue by mapeca** [totaldebug/pyarr#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected feature

Use a function to call a GET request on /api/v3/manualimport and import a file that is stuck and can be manually imported.
![image](https://user-images.githubusercontent.com/32661062/211255067-d288200b-537b-4ce5-8718-40313f6c6c22.png)

### Possible Solutions

I should check so i could talk from a correct perspective. 

### Context / Reason

I dont know others, but in spanish scene is common to have filenames without year, language or quality in title, and that makes radarr to throw "unable to parse". This endpoint would be very useful, so you can automate a script instead of going to the web interface and doing it manually. I know that this is a problem of radarr and should be reported to them, but that does not make this endpoint useless, so you can add quality and language from this api wrapper.
![image](https://user-images.githubusercontent.com/32661062/211255100-b12a722c-1b30-4c8b-b75d-79912326b4dd.png)

Thanks for your work guys

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
This will be added as part of #116
