### ISSUE TITLE
Generate new discord invite link

### ISSUE THREAD

**Issue by Archmonger** [totaldebug/pyarr#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected feature

Functional discord invite link

### Context / Reason

The current discord invite link results in an error when trying to join. This link might need to be regenerated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hey, I just checked and the link is still valid: https://discord.gg/6fmekudc8Q

Was it from the readme or elsewhere that it wasnt working?

**Comment by Archmonger** [comment]
Hmm maybe it was a discord bug with their invite handling. It seems to work now.
