### ISSUE TITLE
Add code examples

### ISSUE THREAD

**Issue by mymy-dot** [totaldebug/pyarr#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected feature

I'd like to see a few examples of common use scenarios in the documentation and maybe an "examples" directory with a few scripts in there.

I normally learn best by look at examples of others and this project is relatively low on examples so I'm having a hard time with it.

### Possible Solutions

It's probably a really easy request to fill. I bet you have plenty of examples you have used yourself. So it would be mostly copy/pasting for you.

### Context / Reason

I guess I'm somewhat learning impaired. I just need examples to really get it. The current documentation is good in its own right, I just need more examples.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
If you look at the tests, there are tons of examples in there that should help
