### ISSUE TITLE
Add Radarr MoviesSearch to post_command

### ISSUE THREAD

**Issue by LRomandine** [totaldebug/pyarr#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected feature

Ability to request Radarr search for a movie via API the same as clicking the "Search Movie" button in the UI.

Opening issue because PRs require an issue.

### Possible Solutions

Edit models/radarr.py to allow calling moviesSearch

### Context / Reason

Ability to search for movies from API.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mymy-dot** [comment]
There should probably also be a test in [test_radarr.py](https://github.com/totaldebug/pyarr/blob/master/tests/test_radarr.py)

**Comment by LRomandine** [comment]
> There should probably also be a test in [test_radarr.py](https://github.com/totaldebug/pyarr/blob/master/tests/test_radarr.py)

Added to PR.
