### ISSUE TITLE
Root Folder error when using add_movie

### ISSUE THREAD

**Issue by Choff3** [totaldebug/pyarr#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

When trying to add a movie to Radarr using `add_movie(movie,root_dir,quality_profile_id)`, an exception is thrown by pyarr and the movie is not successfully added.

### Steps To Reproduce

Use the [add_movie](https://docs.totaldebug.uk/pyarr/modules/radarr.html#pyarr.radarr.RadarrAPI.add_movie) API call by passing in a movie, root dir and quality profile ID. 

### Expected behaviour

The movie is successfully added to Radarr without throwing an exception.

### Pyarr Version

5.2.0

### Python Version

3.11.4

### Example Code

```shell
from pyarr import RadarrAPI
import os

def radarr_monitor_add(missing_films):

    # Set Host URL and API-Key

    host_url = os.getenv('RADARR_HOST')

    # You can find your API key in Settings > General.

    api_key = os.getenv('RADARR_TOKEN')

    # Instantiate Radarr Object

    radarr = RadarrAPI(host_url, api_key)

    quality_profile_num = 0
    quality_profile = radarr.get_quality_profile()[quality_profile_num]['id']

    root_dir_num = 0
    root_dir = radarr.get_root_folder()[root_dir_num]['path']

    for tmdbid in missing_films:
        film = radarr.lookup_movie_by_tmdb_id(tmdbid)
        radarr.add_movie(film,root_dir,quality_profile)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/src/app/./main.py", line 21, in <module>
    main()
  File "/usr/src/app/./main.py", line 18, in main
    radarr_monitor_add(missing_films)
  File "/usr/src/app/radarr_monitor.py", line 26, in radarr_monitor_add
    radarr.add_movie(film,root_dir,quality_profile)
  File "/usr/local/lib/python3.11/site-packages/pyarr/radarr.py", line 111, in add_movie
    movie["rootFolderPath"] = root_dir
    ~~~~~^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
What do you get if you print out the root_dir variable?

**Comment by Choff3** [comment]
'/movies' which is the path of my default root_dir.

**Comment by marksie1988** [comment]
Ok I will need to do some testing, it also looks like the nightly tests are failing so possible the latest build changed something.

**Comment by Archmonger** [comment]
Yeah the arrs tend to change their APIs without notice. Infortunately none of them adhere to version controlled endpoints.

**Comment by marksie1988** [comment]
I have just tested on the latest versions and my tests pass, I used the following code:

```
    quality_profiles = radarr_client.get_quality_profile()
    movie_imdb = radarr_client.lookup_movie(term=f"imdb:{RADARR_IMDB}")
    root_dir = radarr_client.get_root_folder()[0]["path"]

    data = radarr_client.add_movie(
        movie=movie_imdb[0],
        root_dir=root_dir,
        quality_profile_id=quality_profiles[0]["id"],
        monitored=False,
        search_for_movie=False,
        monitor="movieOnly",
        minimum_availability="announced",
    )
```

**Comment by Choff3** [comment]
Weird. Well I'm not sure what I was doing wrong but I ended up just switching to using the Python requests library instead of Pyarr for my project.

**Comment by Archmonger** [comment]
@Choff3 what radarr version are you running

**Comment by Choff3** [comment]
Latest, 4.6.4.7568
