### ISSUE TITLE
SONARR: EpisodeFile

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/pyarr#30]
GET
GET/{id}
DELETE/{id}
PUT/{id}

**Comment by Archmonger** [comment]
Been a while since my 0.9.4 commit, but is this issue not resolved?

If not I'll push whatever parts are needed to close.

**Comment by marksie1988** [comment]
Hey, still not implemented, I've been tied up with other work for a while.

If you have time feel free to pick this up.
