### ISSUE TITLE
Update documentation to reflect name change of "PyArr" to "pyarr"

### ISSUE THREAD

**Issue by Archmonger** [totaldebug/PyArr#50]
As mentioned in the title, seems like after running `pip install pyarr`, the import command `from PyArr import SonarrAPI` no longer works. However, `from pyarr import SonarrAPI` works.
Documentation needs to be updated to reflect these changes.

**Comment by marksie1988** [comment]
Hi There, 

I have just tested and the install is `pip install PyArr` which will then work with the import `from PyArr import SonarrAPI`

if you use lower case then you would have to change that as you stated.
