### ISSUE TITLE
Issue with `<pyarr.radarr_api.RadarrAPI object>.getMovie()`

### ISSUE THREAD

**Issue by slimcdk** [totaldebug/PyArr#53]
Hi

I get this error on the `RadarrAPI` when calling `.getMovie()`
```bash
Traceback (most recent call last):
  File "fetch_movies.py", line 9, in <module>
    print(radarr.getMovie())
  File "/home/slimcdk/.local/lib/python3.8/site-packages/pyarr/radarr_api.py", line 148, in getMovie
    movieId = args[0]
IndexError: tuple index out of range
```
There is no issue with calling `.getSeries()` on the `SonarrAPI`

**Comment by marksie1988** [comment]
@slimcdk thanks, this was fixed in a new release but it's failing quality checks so won't upload to pypi 

Will get this sorted asap

**Comment by marksie1988** [comment]
The latest version should now resolve this issue.
