### ISSUE TITLE
RADARR: V3 API Compatibility

### ISSUE THREAD

**Issue by Archmonger** [totaldebug/pyarr#55]
I've been informed that the Radarr team will be labeling the the v0.2 endpoints as depreciated within the upcoming months. 

We have a few directions PyArr can go in. I've ranked them in order of what I believe is the best options available to us.
1) Wait for the official public release of v3, then remove all v0.2 `RadarrAPI` functions for  and replace them with new v3 functions.
_(preferred, visually the cleanest method to code)_

2) Have an initialization variable within `RadarrAPI` called `use_v3_api` that defaults to `True`. If that is set to true, then define all V3 functions within the class. If the user sets it to false, then the v0.2 functions are defined instead.
_(this will double the size of `RadarrAPI`, but allows for backwards compatibility with minimal code refactoring)_

3) Create a `RadarrV3API` class, and keep the current `RadarrAPI` class as is. Maintain both as necessary.
_(may lead to confusion in the future where 0.2 becomes obsolete)_

4) Have v0.2 and v3 functions all publicly available within the same class at the same time.
_(will lead to incompatibility issues if the user is using v0.2)_

I will develop the implementation we agree on whenever the Radarr team finishes their API docs. That's likely gonna be six months to a year from now, so we have a lot of time to discuss.

**Comment by marksie1988** [comment]
Leaning towards option 1 if I'm honest, however I guess it would depend how different the API is as to wether we would make it backwards compatible whist it's easy, then as it gets more difficult we can deprecate with warnings.

**Comment by Archmonger** [comment]
From what I've seen so far, the v3 endpoint is a huge overhaul. I don't think we're going to be able to migrate any of our v0.2 code over.
