### ISSUE TITLE
Movie path is wrong after calling RadarrAPIv3.add_movie

### ISSUE THREAD

**Issue by wthueb** [totaldebug/pyarr#62]
Movie path should be {root_dir}/{movie_title} instead of {root_dir}{movie_title} (notice the slash). I don't think that my Radarr is improperly setup, but maybe most people have the trailing slash included in their root dir. An easy fix would be to use os.path.join. This can easily be patched by just explicitly stating the root dir when calling the function though.

Also, using Radarr's "Movie Folder Format" setting (advanced option under Settings -> Media Management) would be ideal, but I'm not sure that Radarr's API could facilitate that.

**Comment by wthueb** [comment]
Upon further investigation it appears that the [/config/naming](https://radarr.video/docs/api/#/Settings/get-config-naming) endpoint would be useful to get the movie folder format setting.

**Comment by marksie1988** [comment]
Thanks for logging this, the quick fix is like you say to just use os.path, however I would like to use the naming config as you found later on. However i'm trying to figure out how to convert the naming params into a path as the params available in the UI dont match the API, i may need to add some conversion to the correct value.

**Comment by wthueb** [comment]
I'll look into this if I find some time as well.

**Comment by marksie1988** [comment]
I did some testing and its possible to just use `rootFolderPath` then Radarr will name the folder appropriately.
