### ISSUE TITLE
Cannot read property 'forEach' of undefined type: 

### ISSUE THREAD

**Issue by osmanboy** [totaldebug/pyarr#68]
Just installed like showed in you guide :

You need HACS installed and configured
Go to plugins tab
Search for Atomic Calendar Revive
If you use the Lovelace Editor then first go to your user provile and enable Advanced Mode
Now add the follwoing to Configuration -> Lovelace Dashboards -> Resources
/hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js

## Expected behavior
Now i wanted to add it to my dashboard but this doesnt work

## Current behavior
Cannot read property 'forEach' of undefined
type: 'custom:atomic-calendar-revive'
name: Calendar Card
enableModeChange: true

## Screenshot
https://i.imgur.com/h5DTY8v.png

**Comment by marksie1988** [comment]
Hey there, 

looks like you posted this to the wrong project, however looking at the config you haven't defined any entities.  

If this doesn't work please post on the atomic calendar issues board.
