### ISSUE TITLE
set_command's **kwargs removed from 2.0.1

### ISSUE THREAD

**Issue by Archmonger** [totaldebug/pyarr#74]
I think you accidentally removed the kwargs for set_command, which fundamentally breaks most of the commands.

The kwargs are needed in order to input some additional arguments. These arguments aren't consistent across commands, so it needs a kwargs.

**Comment by marksie1988** [comment]
Yea I see, not sure what I did there! 

I'll fix that this morning and get a release out.

**Comment by Archmonger** [comment]
I was going to PR it but I have no idea how to do the proper kwargs syntax for Sphinx.

On a side note, we are definitely going to want a page to show users how to contribute to the docs (if need be). Similar to my [Conreq /docs/contrib/](https://archmonger.github.io/Conreq/contrib/docs/) page.
