### ISSUE TITLE
Add Readarr support

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/pyarr#80]
Adding Readarr API support for e books

# General

- [x] Get Calendar

# Library

- [x] get book 
- [x] Lookup Book
- [x] Add Book
- [x] Edit Book
- [x] Delete Book
- [x] Lookup Author
- [x] Add Author
- [x] Edit Author
- [x] Delete Author

- [x] List books
- [ ] Mass Edit

# Activity

- [x] Get Queue
- [ ] Update item in Queue
- [x] Delete item in queue
- [x] get History
- [x] Get Blacklist
- [x] Delete Blacklist

# Wanted

- [x] Get Missing
- [x] Get Cutoff Unmet

# Settings

- [x] Get root folder
- [x] set root folder
- [ ] update root folder
- [x] delete root folder
- [x] get remote path mappings
- [x] get book naming
- [x] get media management
- [ ] update media management
- [x] get profiles
- [ ] add profiles
- [x] edit profiles
- [x] delete profiles
- [x] get quality definitions
- [x] edit quality definitions
- [x] get indexers
- [ ] add indexers
- [x] update indexers
- [x] delete indexers
- [x] get download clients
- [ ] add download clients
- [x] update download clients
- [x] delete download clients
- [x] get import lists
- [ ] add import lists
- [x] update import lists
- [ ] delete import lists
- [x] get notification
- [ ] add notification
- [x] edit notification
- [x] delete notification
- [x] get metadata provider
- [x] edit metadata provider
- [x] get tags
- [x] add tags
- [x] edit tags
- [x] delete tags
- [x] get tags detailed
- [x] get host
- [x] edit host
- [x] get ui 
- [x] update ui

# System
- [x] get status
- [x] get health
- [x] get disk space
- [x] get history
- [x] get task
- [ ] post task
- [x] get command
- [x] post command
- [x] get backups
- [ ] add backup
- [x] get updates
- [x] get log
- [x] get log file

**Comment by Archmonger** [comment]
Hey @marksie1988 can create a draft PR of `80-add_readarr_support` and link it ("Linked pull requests" on the sidebar) to this issue for better tracking and visibility?

**Comment by marksie1988** [comment]
@Archmonger Just after your opinion on this one. 

Currently when we `add_movie` or `add_series` we run `_construct_xxx_json` im wondering if a better way to do this would be to input the object rather than the IDs for example:

```
def add_book(self, book, quality_profile, other_vars):

   params_json = {
      "title": book["title"],
      "qualityProfileId": quality_profile["id"]
   }
   <other code here>

add_book(self.lookup_book("goodreads:123"), self.get_quality_profiles("1"), other_vars)
```

so rather than a user supplying the IDs and then doing a lookup, the lookup data is supplied as part of adding the book. this would be the same for the quality profile and any others that rely on functions within the API.

I haven't implemented or tested this yet, currently just a theory and may be that the way its currently done is best, but wanted to see what you thought.

**Comment by Archmonger** [comment]
The way it's currently being done is about the most "user friendly" way it could be implemented. Having the user supply the object would be less convenient.

Another option is to just use a dataclass rather than a dict, but that would really only make the current implementation less readable.

The only improvement I could think of it's optionally letting the user pass his own `object=...` as a kwarg. That would allow for forcibly overriding some values if needed, but that's still unnecessary complication since the best practice would be to use `upd_*` to change the value after the fact.

**Comment by marksie1988** [comment]
Ok after thinking about it you are probably right, assuming the user will understand passing the record rather than just an I'd may cause confusion and as doing a lookup in the construct isn't a major overhead it makes little sense to do it another way. 

I'll also see what the required fields are for adding books as I think it may be more that sonarr/radarr require and the construct could get messy. 

I'll do some testing and see
