### ISSUE TITLE
Add Lidarr support

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/pyarr#81]
Add Lidarr API for music support

**Comment by jordanboucher42** [comment]
Hello,
do you plan to add this feature? I eagerly await it!
Thank you for your excellent work

**Comment by tkdrob** [comment]
> Hello, do you plan to add this feature? I eagerly await it! Thank you for your excellent work

No to take anything away from these guys but I do have an async package with lidarr support in my repos. Check it out if you can use async.

**Comment by marksie1988** [comment]
> Hello, do you plan to add this feature? I eagerly await it! Thank you for your excellent work

Hi, yes we plan to add the feature, unfortunately I have been busy on other projects. I'm hoping to start this work soon.
