### ISSUE TITLE
RadarrAPI.upd_movie does not work

### ISSUE THREAD

**Issue by shunluzhang** [totaldebug/pyarr#94]
## Expected behavior
1. use RadarrAPI.get_movie to get a dict
2. change some value in the dict, for example 'qualityProfileId'
3. use RadarrAPI.upd_movie to update Radarr database
4. used to have no error and Radarr database has been changed with v2.0.7 (call RadarrAPI.get_movie again and verified)

## Current behavior
step 3 returns 'MethodNotAllowed', not error was raised and Radarr database not changed

## Possible reasons and solutions
in RadarrAPI.upd_movie, path = "/api/movie"
in request_handler._request_url, url is defined as f"{self.host_url}/api{ver_uri}/{path}"
ver_uri = '/v3', so _request_url returns https://HOSTNAME/api/v3//api/movie
so there is one extra slash between v3 and api/movie
changed in RadarrAPI.upd_movie, path = "api/movie", program runs successfully

also, according to Radarr API docs, this path value should be just 'movie'
so _request_url should return https://HOSTNAME/api/v3/movie

haven't tested other functions, but did a quick find and in Radarr.lookup_movie_by_imdb_id, path also got one extra leading slash

**Comment by Archmonger** [comment]
Temporary resolution is downgrading to `v2.0.7`. I'll PR a fix for this now.
