### ISSUE TITLE
sonarr missing get_quality_profiles

### ISSUE THREAD

**Issue by shunluzhang** [totaldebug/pyarr#96]
GET /profile
def get_quality_profiles(self):
        """Gets all quality profiles
        Returns:
            JSON: Array
        """
        path = "/api/profile"
        res = self.request_get(path)
        return res

exists in v2.0.7 but missing in v3

**Comment by Archmonger** [comment]
😟

Looks like I didn't review #84 hard enough. I'm going to redo a complete review of it and see if there's anything else missing.

**Comment by marksie1988** [comment]
`get_quality_profile` exists within the base class. Could work without the s on the end.
